a = input('digite algo: ')
print(f'O tipo primitivo desse valor é: {type(a)}')
print('O valor digitado é somente espaços? ', a.isspace())
print('O valor digitado é somente numeros? ', a.isnumeric())
print('O valor digitado é alfabético? ', a.isalpha())
print('O valor digitado é alfanumérico? ', a.isalnum ())
print('O valor digitado é somente minuscola? ', a.islower())
print('O valor digitado é somente maiúscola? ', a.isupper())
print('O valor está capitalizado(maiuscola e minuscola)? ', a.istitle())